In [35]:
import numpy as np

In [36]:
# Кількість елементів у векторі (можна змінити за потребою)
n = 1000

# Створення вектора з квадратними коренями
vector = np.sqrt(np.arange(1, n + 1))

# Виведення вектора
print(vector)

[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335  4.          4.12310563  4.24264069
  4.35889894  4.47213595  4.58257569  4.69041576  4.79583152  4.89897949
  5.          5.09901951  5.19615242  5.29150262  5.38516481  5.47722558
  5.56776436  5.65685425  5.74456265  5.83095189  5.91607978  6.
  6.08276253  6.164414    6.244998    6.32455532  6.40312424  6.4807407
  6.55743852  6.63324958  6.70820393  6.78232998  6.8556546   6.92820323
  7.          7.07106781  7.14142843  7.21110255  7.28010989  7.34846923
  7.41619849  7.48331477  7.54983444  7.61577311  7.68114575  7.74596669
  7.81024968  7.87400787  7.93725393  8.          8.06225775  8.1240384
  8.18535277  8.24621125  8.30662386  8.36660027  8.42614977  8.48528137
  8.54400375  8.60232527  8.66025404  8.71779789  8.77496439  8.83176087
  8.88819442  8.94427191  9.          9.05538514  9.11043358 

In [37]:
# Створення двовимірного масиву розміром 3x3 з залишками від ділення на 3
matrix = np.arange(1, 10).reshape(3, 3) % 3

# Виведення матриці
print(matrix)

[[1 2 0]
 [1 2 0]
 [1 2 0]]


In [38]:
# Розмірність масиву
rows, cols = 9, 9

# Створення масиву розміром 9x9 з випадковими натуральними числами від 1 до 50
matrix = np.random.randint(1, 51, size=(rows, cols))

# Знайдемо відсоток чисел, які діляться на 3 без остачі
divisible_by_3 = (matrix % 3 == 0)
percentage_divisible_by_3 = (np.sum(divisible_by_3) / (rows * cols)) * 100

# Виведення результатів
print("Матриця:")
print(matrix)
print("\nВідсоток чисел, які діляться на 3 без остачі:", percentage_divisible_by_3, "%")

Матриця:
[[16  5 40  2  8 46 37 13  7]
 [13 21 26 36 48  3 13 24 23]
 [22 33  1 37 25 41 43 21  6]
 [49 36 32 42 37 42 15  9 42]
 [46 30  3  7 46 29 27  3 46]
 [39  7 22 17 16 50 36 49 22]
 [11 18 30 42  3  3 13 44 46]
 [26 39 32 22 12 14 42 43 15]
 [47 32  4 37 27  5 25 45  2]]

Відсоток чисел, які діляться на 3 без остачі: 38.2716049382716 %


In [39]:
matrix = np.random.uniform(-0.9, 0.9, size=(4, 4))
print(matrix)

[[-0.44209868 -0.05406291  0.09146476 -0.38029363]
 [-0.67278227 -0.77310697  0.86627969 -0.15833691]
 [-0.61926952 -0.29535802  0.17467575 -0.43552619]
 [-0.33547014 -0.39520165  0.31118402 -0.10434101]]


In [40]:
# Створення двох масивів розміром 7 з випадковими цілими числами від 1 до 5
array1 = np.random.randint(1, 6, size=7)
array2 = np.random.randint(1, 6, size=7)

# Виведення двох масивів
print("Перший масив:", array1)
print("Другий масив:", array2)

# Виконання поелементного додавання, віднімання та множення
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

# Виведення результатів
print("Результат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)


Перший масив: [5 5 2 2 3 4 5]
Другий масив: [5 5 5 3 3 1 5]
Результат додавання: [10 10  7  5  6  5 10]
Результат віднімання: [ 0  0 -3 -1  0  3  0]
Результат множення: [25 25 10  6  9  4 25]


In [41]:
# Створення двох векторів розміром 4 з довільними дійсними числами
vector1 = np.array([2.0, 3.0, 1.5, 4.2])
vector2 = np.array([1.0, 2.0, 0.5, 3.0])

# Обчислення скалярного добутку
scalar_product = np.dot(vector1, vector2)

# Виведення результату
print("Перший вектор:", vector1)
print("Другий вектор:", vector2)
print("Скалярний добуток:", scalar_product)

Перший вектор: [2.  3.  1.5 4.2]
Другий вектор: [1.  2.  0.5 3. ]
Скалярний добуток: 21.35


In [42]:
# Створення двох матриць розміром 2x3 та 3x4 з випадковими цілими числами від 1 до 15
matrix1 = np.random.randint(1, 16, size=(2, 3))
matrix2 = np.random.randint(1, 16, size=(3, 4))

# Виведення двох матриць
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

# Перемноження матриць
result_matrix = np.dot(matrix1, matrix2)

# Виведення результату
print("\nРезультат перемноження матриць:")
print(result_matrix)


Перша матриця:
[[ 3 13 14]
 [12 11  3]]

Друга матриця:
[[ 7 12  3 10]
 [15  9  2 13]
 [ 1  6  8  4]]

Результат перемноження матриць:
[[230 237 147 255]
 [252 261  82 275]]


In [43]:
matrix = np.random.randint(1, 16, size=(2,3))

# Виведення початкової матриці
print("Початкова матриця:")
print(matrix)

# Знаходження оберненої матриці
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nМатриця не має оберненої матриці (матриця сингулярна).")

Початкова матриця:
[[ 2 10  7]
 [ 3  8  3]]

Матриця не має оберненої матриці (матриця сингулярна).


In [44]:
# Створення матриці розміром 3x3 з випадковими цілими числами від 3 до 15
matrix = np.random.randint(3, 16, size=(3, 3))

# Виведення початкової матриці
print("Початкова матриця:")
print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

# Виведення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[13  9 14]
 [15 14 13]
 [13  9  6]]

Транспонована матриця:
[[13 15 13]
 [ 9 14  9]
 [14 13  6]]


In [45]:
# Створення матриці розміром 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створення вектора розміром 4 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=4)

# Виведення матриці і вектора
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

# Обчислення добутку матриці на вектор
result = np.dot(matrix, vector)

# Виведення результату
print("\nРезультат добутку матриці на вектор:")
print(result)

Матриця:
[[7 9 1 2]
 [9 5 6 4]
 [8 3 2 9]]

Вектор:
[9 2 3 9]

Результат добутку матриці на вектор:
[102 145 165]


In [46]:
# Створення матриці розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора розміром 3 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3)

# Виведення матриці і вектора
print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

# Обчислення добутку матриці на вектор
result = np.dot(matrix, vector)

# Виведення результату
print("\nРезультат добутку матриці на вектор:")
print(result)

Матриця:
[[0.76079049 0.9525531  0.58044082]
 [0.69273241 0.97621956 0.6160667 ]]

Вектор:
[0.09786938 0.7335963  0.87407769]

Результат добутку матриці на вектор:
[1.28059789 1.32243851]


In [47]:
# Створення матриці розміром 8x8 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(8, 8))
# Створення матриці 2 розміром 8x8 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(8, 8))

# Виведення матриці
print("Матриця:")
print(matrix1)

# Знаходження добутку всіх елементів матриці
product_of_elements = np.prod(matrix1)

# Виведення результату
print("\nДобуток всіх елементів матриці:", product_of_elements)

Матриця:
[[ 7  6  4  4  7  6  5  7]
 [ 8  3  1 10  2  1  1  7]
 [ 7  3  7  2  8  8  3  7]
 [ 2  7  6  2  8  5  9  5]
 [10  2  8  7  4  5  5  7]
 [10  5  6  5  6  7  6  3]
 [ 7  5  9  3  7 10  8  2]
 [ 1  4  5  9  4  3  3  3]]

Добуток всіх елементів матриці: -4948840263968620544


In [48]:
# Створення двох матриць розміром 7x7 з випадковими дійсними числами від -1 до 1
matrix1 = np.random.uniform(-1, 1, size=(7, 7))
matrix2 = np.random.uniform(-1, 1, size=(7, 7))

# Виведення першої матриці
print("Перша матриця:")
print(matrix1)

# Виведення другої матриці
print("\nДруга матриця:")
print(matrix2)

# Знаходження різниці елементів матриць
difference_matrix = matrix1 - matrix2

# Виведення результату
print("\nРізниця елементів матриць:")
print(difference_matrix)

Перша матриця:
[[-0.66536181  0.87316065  0.89649007 -0.40331768  0.25999625 -0.98524229
  -0.1762533 ]
 [ 0.01275605 -0.69487464 -0.38791848 -0.73866422 -0.02474177 -0.06322643
   0.0173507 ]
 [-0.90473312  0.28232128  0.28046414 -0.24258723 -0.06983707  0.32424825
   0.64486719]
 [-0.62801076  0.32765394 -0.04097032 -0.58439228 -0.16625106  0.33985357
   0.40904733]
 [ 0.86116825  0.01615077  0.14840697  0.30696166 -0.55498539 -0.84229512
   0.03762515]
 [-0.38646903 -0.42675307 -0.02946116  0.9435484  -0.60963638  0.30105701
  -0.21235575]
 [ 0.10373453 -0.93493194 -0.75744943  0.80926614  0.23103521  0.55599119
  -0.61534448]]

Друга матриця:
[[ 0.92485873  0.23322124  0.06624582 -0.54455229 -0.33015537  0.39408961
   0.35761826]
 [ 0.41645624  0.73807308 -0.10977101 -0.55942639  0.69010511  0.39447596
  -0.63435776]
 [-0.13483961  0.61321808  0.42802338 -0.87380353 -0.78472457 -0.9994769
   0.24381809]
 [ 0.00391186  0.08383708 -0.51248787 -0.40682714 -0.11193501 -0.52005618
  -0.

In [49]:
# Створення матриці розміром 9x9 з випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(9, 9))

# Виведення матриці
print("Матриця:")
print(matrix)

# Знаходження суми елементів на головній діагоналі
diagonal_sum = np.trace(matrix)

# Виведення результату
print("\nСума елементів на головній діагоналі:", diagonal_sum)

Матриця:
[[ 9.94287357 -1.71684633 -8.69810746 -6.54515924 -8.68935175  4.96122961
  -9.04424408  7.53550243  0.64726736]
 [-7.34741598  1.24238872 -1.3878705   4.41763589 -9.63863803  2.41576911
   2.89897293  4.31199925  6.86833421]
 [ 5.70617981 -9.52379094 -7.40698246 -1.41499465 -0.22434058  6.84417331
   0.52955222 -8.85003205 -6.21318156]
 [-6.35072449  5.03812095 -1.66583407 -0.52554919  5.81257406  9.78798666
  -7.48332933 -6.58970793  2.18874321]
 [-6.1000852   6.36931639  8.70864163  7.00536459 -0.42813095 -5.02550746
   1.02793283  3.43946924  8.61358655]
 [ 9.19834148  7.80585946 -0.35426459 -8.48639708  5.3239425   9.35720058
   9.74134715  5.64151962 -5.89309383]
 [-3.48210169  2.19834285 -0.11787008  8.68706188  9.20740602 -8.20293831
   6.41565534  8.56663567 -5.90272423]
 [-3.67945011 -1.55132446 -6.93820439  0.45684284 -3.49127164  9.12140804
   4.98407645 -6.78438049  9.16979176]
 [ 1.60703929  0.41903405  7.82011325  5.64928858  6.62292394  5.02731609
   7.83118371

In [50]:
# Створення матриці розміром 9x9 з випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, size=(9, 9))

# Виведення матриці (не обов'язково)
print("Матриця:")
print(matrix)

# Знаходження вектору-стовпчика з сумами елементів кожного стовпця
column_sums = np.sum(matrix, axis=0)

# Виведення результату
print("\nВектор-стовпчик з сумами елементів кожного стовпця:")
print(column_sums)

Матриця:
[[ 0.40064709  0.36260193  0.32182973 -0.39081394 -0.26786    -0.12123729
  -0.30942723  0.16678574  0.32370635]
 [-0.44462016  0.40352531  0.22226368 -0.01959028  0.20899928 -0.33922379
   0.12484784  0.3616198   0.00054228]
 [ 0.01676211 -0.03707723 -0.22255428  0.36595278  0.16031148  0.43874256
  -0.3585578   0.46407501  0.19958238]
 [ 0.24513777  0.01894586  0.04129981  0.45714269 -0.32810111 -0.19536186
  -0.02748035  0.26651495 -0.03775127]
 [-0.26342891 -0.22086754 -0.04821373 -0.0286857  -0.13465535  0.00571586
   0.33174446 -0.22474157 -0.21303926]
 [ 0.2384623  -0.02273685  0.44769773  0.43520709 -0.24848803 -0.38444207
  -0.14075715  0.42425187 -0.24900284]
 [-0.10480461  0.01560409  0.3969193  -0.0168409  -0.06736867 -0.04463864
   0.17385082  0.4594492   0.00195424]
 [-0.25395709 -0.27794855 -0.36811264 -0.32368475 -0.04022281 -0.25349744
   0.08403286 -0.03284159  0.40446039]
 [ 0.01503511 -0.4131247   0.00799143  0.16402504 -0.34979579 -0.08193228
   0.15394394